### ISSUE TITLE
Proposal writing

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Group_10#22]
EDA can only show correlations, not associations - this is mis-stated in the last sentence of the first paragraph of your proposal. Be careful with using the correct language.

**Comment by ttimbers** [comment]
- You should specify what C is, and what kind of regularization you are doing. And explain why you chose logistic regression over something like k-nn or SVM (I am guessing it probably was for the sake of interpretability?)

- What is the impact of the class imbalance? Will you need to do anything to address this, and if so, what will you do?

**Comment by ChuckHo777** [comment]
> * You should specify what C is, and what kind of regularization you are doing. And explain why you chose logistic regression over something like k-nn or SVM (I am guessing it probably was for the sake of interpretability?)
> * What is the impact of the class imbalance? Will you need to do anything to address this, and if so, what will you do?
