### ISSUE TITLE
Milestone 2 General Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/DSCI_522_Group_10#55]
Hello Group 10!

I found your project very interesting, and well thought-outt.

Here are some comments on your Report:
1) Fig 3: no x-axis, and lots of different value ranges on the x-axis. An explanation that the y-axis is density would be nice
2) Fig 4: making a bar graph with one bar per feature for each model would be nicer and easier to look at than a table. Or at least an explanation that the table is ordered from lowest to highest Roc_Auc
3) Tables should be titled with 'Table' instead of 'Figure' (Figure 4 and 5)
4) Table of contents missing in report
5) Fig 3: x-axis labels would be helpful

**Comment by anodaini** [comment]
Feedback addressed! Thank you Analise!
