### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/DSCI_522_Group_10#60]
Hi! Your project looks good and you got some interesting results. Here are some things I noticed while reading that you might want to think about:

**README file:**
- The conda environment did not install for me… this could be my issue as conda environments have a 50% success rate on my computer.  Hopefully a Docker container will fix this.
- There are no instructions for running the Makefile.

**Report**:
Summary:

- You say “We were more focused on reducing false negatives to capture more revenue.” You should clarify this connection. How are false negatives related to revenue?

- If the F1 score is not good enough, what score would you consider to be good enough?

- You mention that “we were using the f1-score as the main metric but had a bias of recall over precision”, What does this mean? That you will use F1? Recall? Use recall as a tie-breaker in the case of equal F1 scores?

- The reference the article on telemarketing is from 1991, which seems out of data considering how our relationships to phones have evolved since then.

Results & Discussion:

- Since you refer to features like `previous outcome`, `Euribor 3 Month Rate`, `Employment Variation Rate`, etc, it would be nice to see a description of what these mean.

- In Figure 3 the plot legends say Not Purchased/Purchased but the figure caption refers to Subscribers/Non-subscribers. Consistent terminology would be more clear.

- Figure 4 and figure 5 don’t render correctly in the .md report when seen on github.

- When referring to sklearn parameters like max_iter, the parameter names should be in a different typeface (italic, etc) for readability.

Good luck with the rest of the project!

**Comment by ChuckHo777** [comment]
Thanks for the feedback, will look into it.

**Comment by anodaini** [comment]
Addressed! Thank you Trevor!
