### ISSUE TITLE
Peer review from Jason Chang

### ISSUE THREAD

**Issue by jachang0628** [UBC-MDS/DSCI_522_Group_10#69]
Hi guys, sorry for the late review.

I think you guys have a very interesting project and I enjoyed reading your analysis. Everything is easy to follow and flows nicely. 

In terms of area of improvement:

Documentation:
Everything is nicely documented(this includes packages, sites, as well as data). Good Job!

Code:
I am able to run your analysis via the makefile, which is great. However, I am unable to see the figures for Fig1, Fig2, and Fig3 in the rendered HTML document. All other figures were successfully loaded. In terms of reproducibility, I was able to reproduce your results on my machine.  The codes are very well written and documented.

Analysis:
I find your analysis reasonable and agree with the results you have gotten. Just a small suggestion thought, you mentioned you picked logistic regression not only because it has the best performance, but also for its interpretability. Hence, maybe you guys could interpret on some of the features that are influencing the prediction.

Communication:
The report flows nicely and I found it easy to follow along. The conclusion is coherent with the summary. 

Suggestions:
Again, maybe do some interpretation on the features and what sort of effect do they have on your prediction. In addition to that, maybe you can order them via coefficient magnitude and show the audience what the most important features are. 

Good job on your project and all the best for Milestone 4. !

**Comment by ChuckHo777** [comment]
Thank you for the feedback. We will look into it.

**Comment by jufu** [comment]
Thanks again. We will take these up as future enhancements (if we continue this project next term)!  Cheers.
