### ISSUE TITLE
Peer review by Daniel Ortiz

### ISSUE THREAD

**Issue by danielon-5** [UBC-MDS/DSCI_522_Group_10#70]
Hi folks!

First of all let me congratulate you for such a great work. I can see a lot of effort in it. I would like to first address my favorite highlights:
- The code and scripts are high quality
- Really good and clear README
- I appreciated the way you were constantly making references
- Great Model selection histogram (figure 4 on the report), it was very clear
- The report is also very well done, good conclusions and good suggestions for future improvements
- The yaml file and the usage instructions are impecable

Few pieces of advice that I could give you:
- The f1 and recall scores could be explained in a better and more basic way so it can be more comprehensible to a wider audience
- On the EDA, I felt that the figure 1 could be better explained to be better understood. I wonder what the correct definition is for the values in the categorical value "Previous outcome"
- Density plots are very hard to interpret for most audiences. Maybe figure 3 could be explained more clearly and slowly
- Maybe addressing the class imbalance issue at the beginning of the EDA so it makes more sense when explaining the 'Logistic Regression (balanced)' model 

Since it really is a great project and I have no more pieces of advice, I will point out small typos or minor details just to feel that I can give more than just a couple of suggestions: 
- I wonder why in figure 2 of the report the months of January and February are not present
- More consistency on regular terms throughout the README and report. For example, I noticed "f1-score", "f-1 score", and "f1_score"
- Few typos encountered such as "whether" that is duplicated on the first paragraph under the 'Analysis' section on the report or "Logistice Regression" in README file or "Comfusion matrix" on figure 5 of the report
- I also noticed many many .png files on the results directory. I wonder if they were all useful and how or where they were used

I again want to say great job. Reading and going through your project already gave me a lot of ideas to make my future projects better so also thank you for that.

**Comment by jufu** [comment]
Thank you for the feedback. We will take these up as future enhancements (if we continue this project next term)!  Cheers.
